import { ReactElement } from 'react';
import Head from 'next/head';

import { Layout } from '../components/Layout/Layout';


const Page = () => {
  return (
    <>
      <Head>
        <title>Blog - Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}

Page.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}

export default Page;